# Generated by Django 5.0.1 on 2024-01-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("talla", "talla")], max_length=100
            ),
        ),
    ]
